### ISSUE TITLE
[ENHANCEMENT]Cooldown Exhaustion? 

### ISSUE THREAD

**Issue by ghost** [Fuzss/swordblockingmechanics#11]
I was wondering if you could add a feature that would only allow the player to swing their sword/tool, if the the cooldown was over. There are other mods that do this, though none of them (to my knowledge) are updated to 1.14.4. Obviously this would be a separate config option. I believe that this would really allow a lot of customization for modpack devs to have the player play differently, make the pack harder, etc. Hopefully you will continue to updated this mod with some of the community suggestions in the future. I really appreciate it.

**Comment by Fuzss** [comment]
This feature was added a while back to another mod of mine (although disabled by default as that mod focuses on different combat mechanics): https://www.curseforge.com/minecraft/mc-mods/golden-age-combat
