### ISSUE TITLE
[Bug]: Sword Blocking animation doesn't work

### ISSUE THREAD

**Issue by mathisgpnpv** [Fuzss/swordblockingmechanics#16]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

v3.0.0.531

### Notes (Required)

I launch my game with this mod :
SwordBlockingMechanics-v3.0.0.531-1.18.2-Fabric.jar
GoldenAgeCombat-v3.4.0.530-1.18.2-Fabric.jar

And when i want to block sword, the animation on first person doesn't work, but on third person the animation work well

**Comment by Fuzss** [comment]
Fixed in v8.0.1.
