### ISSUE TITLE
Modded Swords in MC 1.20.1

### ISSUE THREAD

**Issue by OysterStew** [Fuzss/swordblockingmechanics#17]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

GoldenAgeCombat-v8.0.0-1.20.1-Forge and SwordBlockingMechanics-v8.0.0.542-1.20.1-Forge

### Notes (Required)

Using a Compressed Diamond Sword from Ultimate Compression Mod. Cannot block or parry. Vanilla swords do block and parry. Do not know how many other config settings are actually being applied or not.

**Comment by Fuzss** [comment]
Swords that are to support blocking are defined in the `swordblockingmechanics:can_perform_sword_blocking` item tag. By default this tag includes the `minecraft:swords` item tag. Mod authors should generally add their own swords to this vanilla item tag and Sword Blocking Mechanics will pick them up automatically.

You can either ask the author of Ultimate Compression Mod to add their swords to the vanilla tag, do it yourself, or add their swords to `swordblockingmechanics:can_perform_sword_blocking`.

**Comment by OysterStew** [comment]
Thank you for the detailed answer :)
