### ISSUE TITLE
[Suggestion]: Сooldown after parry 

### ISSUE THREAD

**Issue by Vampzula** [Fuzss/swordblockingmechanics#20]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.20.1

### Mod Version(s) (Optional)

8.0.1

### Suggestion (Required)

I really liked the idea of the mod, which cleverly rethinks the old system of blocking with a sword, but I have a proposal to add a cooldown of 1.5+ seconds so that the parry mechanics cannot be overused

Thanks to the mod, I can practically parry all of Warden's attacks

thanks google translator

**Comment by Fuzss** [comment]
The parry mechanic already works exactly like this. There is a cooldown which you can see by the shield indicator, while it is recharging you cannot activate the parrying ability.

For sword blocking itself I don't think it's necessary to have a cooldown, the mechanic is similar to the vanilla shield but just a lot weaker.
