### ISSUE TITLE
[Suggestion]: Disable sword blocking for specific modded weapons

### ISSUE THREAD

**Issue by NolanHewitt** [Fuzss/swordblockingmechanics#22]
### Mod Loader (Optional)

Quilt

### Minecraft Version(s) (Optional)

1.20.1

### Mod Version(s) (Optional)

8.0.1

### Suggestion (Required)

It would be nice if there was some way to disable sword blocking for certain weapons. I'm using Marium's Soulslike Weaponry mod and the sword blocking mechanic prevents some of its weapons from being able to activate their ability, but I'd still like to have sword blocking on for the weapons it works with.

**Comment by NolanHewitt** [comment]
Nevermind you can do this with tags through a datapack

**Comment by scarls686** [comment]
What should I do to disable the blocking of certain items?

**Comment by Fuzss** [comment]
Feel free to ask for help on our server: https://lunapixel.studio/discord
