### ISSUE TITLE
[Suggestion]: add compatibility with several datapacks

### ISSUE THREAD

**Issue by GitJason33** [Fuzss/swordblockingmechanics#25]
### Mod Loader (Optional)

Forge

### Minecraft Version(s) (Optional)

1.20.1

### Suggestion (Required)

i suggest you to add a generic support for any swords or axes to be able to parry, and add in configs a whitelist of any sword that doesnt automatically support blocking.

**Comment by Fuzss** [comment]
See https://github.com/Fuzss/swordblockingmechanics/blob/main/1.20.4/Common/src/generated/resources/data/swordblockingmechanics/tags/items/can_perform_sword_blocking.json
